spring:
  datasource:
    url: jdbc:mysql://172.31.43.152:3306/owlsgame?useSSL=false&serverTimezone=UTC
    username: owluser
    password: OwlsApp2025!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect